messagebus-up:
	docker compose -f messagebus.docker-compose.yaml up -d

messagebus-stop:
	docker compose -f messagebus.docker-compose.yaml stop
	
messagebus-down:
	docker compose -f messagebus.docker-compose.yaml down

