# Docker Compose file for the Sentiment Signals Feature Pipeline

name: cryptopredict-sentiment-signals

networks:
  cryptopredict-messagebus_cryptopredict-network:
    external: true

services:
  # ----------------------------------------
  # --- News service
  # ----------------------------------------
  news:
    container_name: news
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        SERVICE_NAME: news
        PORT: 8005
    command: fastapi dev app/services/news/news --port 8005
    ports:
      - 8005:8005
    environment:
      - NEWS_BROKER_ADDRESS=redpanda:9092
    env_file:
      - ../services/news/.env
    restart: always
    networks:
      - cryptopredict-messagebus_cryptopredict-network
